# Generated by Django 6.0.4 on 2026-04-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('event_category', models.CharField(choices=[('tech', 'Tech'), ('music', 'Music'), ('sports', 'Sports')], default='tech', max_length=50)),
                ('event_image', models.ImageField(upload_to='event_images/')),
                ('event_price', models.PositiveIntegerField()),
                ('event_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
