# Generated by Django 6.0.4 on 2026-04-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_name', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='banner_images/')),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
