# Generated by Django 6.0.4 on 2026-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='available_seats',
            field=models.IntegerField(default=5, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_location',
            field=models.CharField(default=5, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='total_seats',
            field=models.IntegerField(default=10, max_length=3),
            preserve_default=False,
        ),
    ]
