# Generated by Django 6.0.4 on 2026-04-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_bookings_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='ticket_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
