# Generated by Django 6.0.4 on 2026-04-14 12:27

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_bookings_ticket_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='banner_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='banner_images'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='id_proof_image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='id_proofs'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='event_images'),
        ),
    ]
